- name: Wired Connection
  become: True
  nmcli:
    conn_name: MRover
    state: present
    type: ethernet
    ifname: {{ ifname }}
    autoconnect: yes
    ip4: 10.1.0.10/8
    gw4: 10.1.0.2
    dns4: [10.1.0.2]
    method6: disabled
