- name: Hold Jetson Kernel Packages Constant
  dpkg_selections:
    name:
      - nvidia-l4t-display-kernel
      - nvidia-l4t-kernel
      - nvidia-l4t-kernel-dtbs
      - nvidia-l4t-kernel-headers
      - nvidia-l4t-kernel-oot-headers
      - nvidia-l4t-kernel-oot-modules
      - nvidia-l4t-bootloader
    selection: hold
