/**:
  ros__parameters:
    static_cam:
      address: 10.1.0.2 # if using RTP, should be set to IP of basestation
      port: 8081
      # camera source can be one of three options: dev_node, dev_path, or image_topic
      # if no camera source is specified, defaults to videotestsrc
      dev_node: "/dev/static_cam"
      # crop_left: PIXELS
      # crop_right: PIXELS
      # crop_top: PIXELS
      # crop_bottom: PIXELS
      stream:
        pixel_format: YUYV # from v4l2-ctl -d DEV_NODE --list-formats-ext
        width: 640
        height: 480
        framerate: 30
        codec: H264
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 1280
        height: 720
        framerate: 5
    boom_cam:
      address: 10.1.0.2
      port: 8082
      dev_node: "/dev/boomcam"
      stream:
        pixel_format: YUYV
        width: 640
        height: 480
        framerate: 30
        codec: H264
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 1280
        height: 720
        framerate: 5
    mob_cam_left:
      address: 10.1.0.2
      port: 8083
      dev_node: "/dev/mob_cam_left"
      stream:
        pixel_format: YUYV
        width: 640
        height: 480
        framerate: 30
        codec: H264
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 1280
        height: 720
        framerate: 5
    mob_cam_right:
      address: 10.1.0.2
      port: 8084
      dev_node: "/dev/mob_cam_right"
      stream:
        pixel_format: MJPG
        width: 640
        height: 480
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 1280
        height: 720
        framerate: 5
    long_range_cam:
      address: 10.1.0.2
      port: 8085
      image_topic: "/long_range_cam/image"
      stream:
        pixel_format: ABGR32
        width: 640
        height: 480
        framerate: 30
        codec: H264
        bitrate: 1000000
      image_capture:
        pixel_format: ABGR32
        width: 640
        height: 480
        framerate: 30
    zed_mini:
      address: 10.1.0.2
      port: 8086
      dev_node: "/dev/zed_mini"
      crop_right: 672
      stream:
        pixel_format: YUYV
        width: 1344
        height: 376
        framerate: 15
        codec: H265
        bitrate: 1000000
      image_capture:
        pixel_format: YUYV
        width: 2560
        height: 720
        framerate: 15
    zed:
      address: 10.1.0.2
      port: 8087
      image_topic: "/zed/left/image"
      stream:
        pixel_format: ABGR32 # https://www.kernel.org/doc/html/v4.9/media/uapi/v4l/pixfmt-packed-rgb.html
        width: 1280
        height: 720
        framerate: 15
        codec: H264
        bitrate: 1000000
      image_capture:
        pixel_format: ABGR32
        width: 1280
        height: 720
        framerate: 15

boom_streamer:
  ros__parameters:
    camera: "boom_cam"

mob_left_streamer:
  ros__parameters:
    camera: "mob_cam_left"

mob_right_streamer:
  ros__parameters:
    camera: "mob_cam_right"

long_range_streamer:
  ros__parameters:
    camera: "long_range_cam"

static_streamer:
  ros__parameters:
    camera: "static_cam"

zed_mini_streamer:
  ros__parameters:
    camera: "zed_mini"

zed_streamer:
  ros__parameters:
    camera: "zed"

camera_client:
  ros__parameters:
    test: 10
    cameras:
      - "boom_cam"
      - "mob_cam_left"
      - "static_cam"
      - "long_range_cam"
      - "zed_mini"
      - "zed"
    rtp_jitter_ms: 50

