# All units are in SI
# ===================
# Time:     second, hz
# Angle:    radian
# Distance: meter

basestation_gps_driver:
  ros__parameters:
    port: /dev/gps
    baudrate: 38400

gps_linearization:
  ros__parameters:
    world_frame: "map"
    rover_frame: "base_link"

    # Exception, these are in degrees
    ref_lat: 42.293195
    ref_lon: -83.7096706
    ref_alt: 0.0

pose_filter:
  ros__parameters:
    world_frame: "map"
    rover_frame: "base_link"
