# Laptop Camera
laptop_cam:
  ros__parameters:
    device: "video0"

laptop_cam_tag_detector:
  ros__parameters:
    image_sub_topic: "/laptop_cam/image"
    box_pub_topic: "/laptop_cam/tag_boxes"

laptop_cam_streamer:
  ros__parameters:
    camera: "laptop_cam"

laptop_cam_detections:
  ros__parameters:
    camera_name: "laptop"

/**:
  ros__parameters:
    laptop_cam:
      address: 127.0.0.1 # localhost
      image_topic: "/laptop_cam/detections"
      stream:
        pixel_format: YUYV
        width: 640
        height: 480
        framerate: 30
