# Laptop Camera
laptop_cam:
  ros__parameters:
    device: "video0"

laptop_cam_tag_detector:
  ros__parameters:
    image_sub_topic: "/laptop_cam/image"
    box_pub_topic: "/laptop_cam/tag_boxes"

laptop_cam_object_detector:
  ros__parameters:
    image_sub_topic: "/laptop_cam/image"
    box_pub_topic: "/laptop_cam/object_boxes"

laptop_cam_streamer:
  ros__parameters:
    camera: "laptop_cam"

laptop_cam_detections:
  ros__parameters:
    camera_name: "laptop"

/**:
  ros__parameters:
    laptop_cam:
      address: 10.1.0.2 # laptop
      port: 8087
      image_topic: "/laptop_cam/detections"
      dev_node: ""
      dev_path: ""
      stream:
        pixel_format: ABGR32
        width: 640
        height: 480
        framerate: 30
        codec: H265
        bitrate: 1000000
