# All units are in SI
# ===================
# Time:     second, hz
# Angle:    radian
# Distance: meter

superstructure:
  ros__parameters:
    input_topics: [ 'sim_cmd_vel', 'nav_cmd_vel', 'joystick_vel_cmd', 'controller_vel_cmd']
    timeout: 0.5
    rate: 30.0
